import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from './components/NavBar'
import Section from './components/Section'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rifas na Veia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>

      <header>
        <NavBar />
      </header>

      <main>

      <Section/>


      </main>


    </div>
  )
}
